"""add_auth_and_stat_constraints

Revision ID: 9d31d5849395
Revises: 49a0605b7c73
Create Date: 2026-07-19 19:24:27.597729
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '9d31d5849395'
down_revision: str | None = '49a0605b7c73'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'batting_game_stats', ['game_id', 'player_id', 'team_id'])
    op.create_unique_constraint(None, 'pitching_game_stats', ['game_id', 'player_id', 'team_id'])
    op.create_unique_constraint(None, 'players', ['external_player_id'])
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'pitching_game_stats', type_='unique')
    op.drop_constraint(None, 'batting_game_stats', type_='unique')
    # ### end Alembic commands ###
