"""allow_repeated_player_rows

Revision ID: bacdcdbe886d
Revises: 9d31d5849395
Create Date: 2026-07-19 19:36:23.480672
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'bacdcdbe886d'
down_revision: str | None = '9d31d5849395'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('batting_game_stats_game_id_player_id_team_id_key'), 'batting_game_stats', type_='unique')
    op.drop_constraint(op.f('pitching_game_stats_game_id_player_id_team_id_key'), 'pitching_game_stats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('pitching_game_stats_game_id_player_id_team_id_key'), 'pitching_game_stats', ['game_id', 'player_id', 'team_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('batting_game_stats_game_id_player_id_team_id_key'), 'batting_game_stats', ['game_id', 'player_id', 'team_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
